Repository cdacgroup16/streameo, pull requests merged in 2023-10, with the labels that each got.

#99 feat: add auth token in cookie from the backend
  backend/controllers/authControllers.js
  backend/controllers/userControllers.js
Labels: enhancement, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#101 add cookie-parser to parse cookie at the backend
  backend/package-lock.json
  backend/package.json
  backend/server.js
Labels: enhancement, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#102 Add Project Information
  README.md
Labels: documentation, enhancement, good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#103 Add authors' details
  README.md
Labels: documentation, good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED

#104 Add Authors' Github profile links
  README.md
Labels: documentation, enhancement, good first issue, HACKTOBERFEST, HACKTOBERFEST-ACCEPTED
